
enum eqterm_transport_type {
    EQTERM_TRANSPORT_NONE = 1,
    EQTERM_TRANSPORT_PRESCRIBED = 2,
    EQTERM_TRANSPORT_RECHESTER_ROSENBLUTH = 3,
    EQTERM_TRANSPORT_SVENSSON = 4,
    EQTERM_TRANSPORT_DYON = 5
};

