
enum eqterm_transport_type {
    EQTERM_TRANSPORT_NONE = 1,
    EQTERM_TRANSPORT_PRESCRIBED = 2,
    EQTERM_TRANSPORT_RECHESTER_ROSENBLUTH = 3,
    EQTERM_TRANSPORT_SVENSSON = 4,
    EQTERM_TRANSPORT_DYON = 5
};

enum eqterm_E_field_eqn {
    UQTY_E_FIELD_EQN_PRESCRIBED=1,
    UQTY_E_FIELD_EQN_SELFCONSISTENT=2,
    UQTY_E_FIELD_EQN_CIRCUIT=101
};


enum Conf_Time_type
{
	CONF_TIME_INTOR     = -1,
	CONF_TIME_BOHM      = 1,
	CONF_TIME_RLW       = 2,
	CONF_TIME_ITER89    = 3,
	CONF_TIME_ITER97    = 4,
	CONF_TIME_IPB98     = 5,
	CONF_TIME_ITER89_OL = 6,
	CONF_TIME_EIV1      = 7,
	CONF_TIME_EIV2      = 8,
	CONF_TIME_GOLDSTONE = 9,
	CONF_TIME_KAYE_BIG  = 10,
	CONF_TIME_CY        = 11,
	CONF_TIME_OS_OL     = 12,
	CONF_TIME_RL_OL     = 13
};