import numpy as np
import matplotlib.pyplot as plt
import h5py
from scipy.signal import savgol_filter
arr = np.array([-1, 2, 3, -2, -5, 1, 0, 1, -9])
print(str(for i in arr np.max(i, 0)))

hf = h5py.File('TCV65108.h5', 'r')
t_CIII = np.array(hf.get('C-III').get('x'))
cIII = np.array(hf.get('C-III').get('z'))
plt.plot(t_CIII, cIII)
plt.ylabel('C-III')
plt.xlabel('t')
plt.xlim([-0.02, 0.05])
plt.show()

t_H = np.array(hf.get('H-alpha').get('x'))
Halpha = np.array(hf.get('H-alpha').get('z'))
plt.plot(t_H, Halpha)
plt.ylabel('H-alpha')
plt.xlabel('t')
plt.xlim([-0.02, 0.05])
plt.show()

t_FIR = np.array(hf.get('Line-integrated (FIR)').get('x'))
FIR = np.array(hf.get('Line-integrated (FIR)').get('z'))
plt.plot(t_FIR, FIR)
plt.ylabel('Line-integrated (FIR)')
plt.xlabel('t')
plt.xlim([-0.02, 0.05])
plt.show()

t_loop = np.array(hf.get('Loop voltage').get('x'))
V_loop = np.array(hf.get('Loop voltage').get('z'))
V_loop_s = savgol_filter(V_loop, 45, 3)
plt.plot(t_loop, -V_loop, t_loop, -V_loop_s)
plt.ylabel('Loop voltage')
plt.xlabel('t')
plt.xlim([-0.02, 0.05])
plt.show()

t_maxThomson = np.array(hf.get('Maximum (Thomson)').get('x'))
maxThomson = np.array(hf.get('Maximum (Thomson)').get('z'))
plt.plot(t_maxThomson, maxThomson)
plt.ylabel('Maximum (Thomson)')
plt.xlabel('t')
plt.xlim([-0.02, 0.05])
plt.show()

t_fluxD = np.array(hf.get('Particle flux (D2)').get('x'))
fluxD = np.array(hf.get('Particle flux (D2)').get('z'))
plt.plot(t_fluxD, fluxD)
plt.ylabel('Particle flux (D2)')
plt.xlabel('t')
plt.xlim([-0.02, 0.05])
plt.show()

t_Ip = np.array(hf.get('Plasma current').get('x'))
Ip = np.array(hf.get('Plasma current').get('z'))
plt.plot(t_Ip, Ip)
plt.ylabel('Plasma current')
plt.xlabel('t')
plt.xlim([-0.02, 0.05])
plt.show()

t_Vp = np.array(hf.get('Plasma volume').get('x'))
V_p = np.array(hf.get('Plasma volume').get('z'))
a_vec = np.sqrt(V_p / (2 * np.pi ** 2 * 0.89))
plt.plot(t_Vp, a_vec)
plt.ylabel('Minor radius')
plt.xlabel('t')
#plt.xlim([-0.02, 0.05])
plt.show()

t_B = np.array(hf.get('Toroidal magnetic field').get('x'))
B = np.array(hf.get('Toroidal magnetic field').get('z'))
plt.plot(t_B, B)
plt.ylabel('Toroidal magnetic field')
plt.xlabel('t')
#plt.xlim([-0.02, 0.05])
plt.show()

hf.close()